### ISSUE TITLE
babel-loader 6.1.0

### ISSUE THREAD

**Issue by primozs** [qimingweng/static-render-webpack-plugin#2]
Hello,
With babel version 6, render is not working. How would one use this plugin with babel 6+

Error "ERROR in render is not a function" happens here 

```
var render = evaluate(
          /* source: */ source, 
          /* filename: */ self.bundlePath, 
          /* scope: */ undefined, 
          /* noGlobals: */ true);
```

My webpack config:

```
var StaticSiteGeneratorPlugin = require('static-render-webpack-plugin');
var routes = [
  '/',
  '/about',
  '/projects',
  {
    path: '/not-found', 
    output: '/404.html'
  }
];

module.exports = {
  entry: './src/entry.js',
  output: {
    filename: 'bundle.js',
    path: './build',
    libraryTarget: 'umd'
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        query: {
          presets: ['es2015', 'react']
        }
      }
    ]
  },
  plugins: [
    new StaticSiteGeneratorPlugin('bundle.js', routes)
  ]
};
```

entry.js

```
// this is not working
export default function(path, props, callback) {
  callback('<!doctype html><html><head></head><body>HTML!</body></html>');
}

// this is working
module.exports = function(path, props, callback) {
  callback('<!doctype html><html><head></head><body>HTML!</body></html>');
};
```

Cheers
Primoz

**Comment by primozs** [comment]
Actually this works:

```
import React from 'react';
import Root from './Root';

module.exports = function(path, props, render) {
  render('<!doctype html>' + React.renderToString(<Root/>));
};

if (typeof document !== 'undefined') {
  React.render(<Root/>, document);
}
```

It seams that module export must be defined with `module.exports =` not `export default`

**Comment by qimingweng** [comment]
@primozs Thanks for pointing this out and finding a solution. I'm happy to take a PR

**Comment by primozs** [comment]
@qimingweng Hi, this is strange but it works, `module.exports` is important only for entry function, so maybe we can just close this :)
cheers

**Comment by qimingweng** [comment]
@primozs maybe it had to do with your babel 6 presets, did you use the es2015 or stage-0 preset?

**Comment by primozs** [comment]
@qimingweng I tried just es2015, I did not try with stage-0

**Comment by sergeylukin** [comment]
See this plugin for babel 6 that fixes it: https://github.com/59naga/babel-plugin-add-module-exports

Just install `npm i babel-plugin-add-module-exports -D` and add `add-module-exports` to plugins in `.babelrc` or to wherever you configure babel.

**Comment by sergeylukin** [comment]
@qimingweng I think it's worth mentioning that in your tutorial: http://www.qimingweng.com/writing/webpack-static-render
