### ISSUE TITLE
ERROR in render is not a function

### ISSUE THREAD

**Issue by oojacoboo** [qimingweng/static-render-webpack-plugin#4]
I can't seem to get past this error.  I've tried all kinds of things.  Any ideas on what would be causing this?  The logging with webpack-dev-server isn't very good.  So, unfortunately, that's the only output I get...

**Comment by qimingweng** [comment]
In your entry file for webpack, it needs to export a function. Post your entryfile?

**Comment by oojacoboo** [comment]
I actually resolved this by reworking the entry file.  I was looking all over the place for the cause though.  It's unfortunate that the error logging isn't more accurate on where Errors are thrown.

Here is my entry file though, if anyone else comes across this - may help.  It's still not perfect though as I'm getting the following errors...

```
import React from 'react';
import ReactDOMServer from 'react-dom/server';
import { match, RouterContext } from 'react-router';
import Routing from './Routing';
import Logger from './util/Logger';

module.exports = (path, props, callback) => {
  let html = '';

  try {
    match({ routes: Routing, location: path, basename: '/' }, (err, redirect, renderProps) => {
      if (err) {
        throw Error(`${err.message} : ${err.stack}`);
      }

      html = ReactDOMServer.renderToStaticMarkup(
        <RouterContext {...renderProps} />
      );
    });

    callback(html);
  } catch (e) {
    Logger.error(e.message);
  }
};
```

**Current Errors**

> Warning: Failed prop type: Required prop `router` was not specified in `RouterContext`.
>     in RouterContext
> Warning: Failed prop type: Required prop `location` was not specified in `RouterContext`.
>     in RouterContext
> Warning: Failed prop type: Required prop `routes` was not specified in `RouterContext`.
>     in RouterContext
> Warning: Failed prop type: Required prop `params` was not specified in `RouterContext`.
>     in RouterContext
> Warning: Failed prop type: Required prop `components` was not specified in `RouterContext`.
>     in RouterContext
> Warning: [react-router] `<RouterContext>` expects a `router` rather than a `history`
> error: Cannot read property 'listenBeforeLeavingRoute' of undefined
> info: undefined
> Warning: [react-router] `<RouterContext>` expects a `router` rather than a `history`
> error: Cannot read property 'listenBeforeLeavingRoute' of undefined
> info: undefined
> Warning: [react-router] `<RouterContext>` expects a `router` rather than a `history`
> error: Cannot read property 'listenBeforeLeavingRoute' of undefined

**Comment by oojacoboo** [comment]
Okay, I've just updated it and tracked down the issue.  You need to check if `renderProps` isn't undefined and conditionally default to a page/route not being found.

```
module.exports = (path, props, callback) => {
  let html = '';

  try {
    match({
      routes: Routing,
      location: path,
      basename: '/',
    }, (err, redirect, renderProps) => {
      if (err) {
        throw Error(`${err.message} : ${err.stack}`);
      } else if (renderProps) {
        html = ReactDOMServer.renderToStaticMarkup(
          <RouterContext {...renderProps} />
        );
      } else {
        throw Error(`${path} Not Found`);
      }
    });

    callback(html);
  } catch (e) {
    Logger.error(e.message);
  }
};
```

**Comment by qimingweng** [comment]
Ah, I see. You were defining a route for static render that didn't exist for react router? Glad it got resolved

**Comment by oojacoboo** [comment]
Yes, I was and the above code is improved.  However, I'm still getting undefined every time for the `renderProps` variable.  It seems that the match() isn't working properly, for some reason.  The `path` is accurate, so I suspect something with the `Routing` is off.

**Comment by oojacoboo** [comment]
Figured I'd follow bck on this.  I got this all working.  This uses Typescript.  The `Logger` is just a custom wrapper around Winston.  `Routing` is a file with the JSX routes.  

Maybe this helps someone else.

```
///<reference path="../node_modules/@types/react-dom/react-dom.server.d.ts" />
declare var module: any;

import * as React from 'react';
import * as ReactDOMServer from 'react-dom/server';
import { RouterContext, match, createRoutes } from 'react-router';
import Logger from 'util/Logger';
import Routing from './Routing';

interface GenerateStaticHTML {
  (html: string): string;
}

module.exports = (path: string, props: {}, callback: GenerateStaticHTML) => {
  let html = '';
  const routes = createRoutes(Routing);

  try {
    match({
      routes,
      location: path,
    }, (err, redirect, renderProps) => {
      if (err) {
        throw Error(`${err.stack}`);
      } else if (redirect) {
        Logger.info(`Redirecting: ${redirect}`);
      } else if (renderProps) {
        html = ReactDOMServer.renderToStaticMarkup(
          <RouterContext {...renderProps} />
        );
      } else {
        throw Error(`${path} Not Found`);
      }
    });

    callback(html);
  } catch (e) {
    Logger.error(`${e.stack}`);
  }
};
```
