### ISSUE TITLE
What's included in bundle.js ?

### ISSUE THREAD

**Issue by oojacoboo** [qimingweng/static-render-webpack-plugin#5]
So, just ran the production generation of the files and it mostly looks good.  However, I noticed that the bundle.js file generated is over 1MB!  I don't have anything within my package.json "dependencies" prop.  Everything is within "devDependencies".

So, my questions is, what's used to determine what's included within the bundle.js.  With static html sites, there isn't a need to include all kinds of client libs, etc.  In general, I would assume, most people are going to want very little js, and certainly not all the dev bootstrapping.

For instance, I see all my html with the React.createElement all through the bundle.  Is the main idea for this project, isomorphic, or static html pages, or both?  I'd be nice to have more control over what's getting output for the bundle.  Does this plugin actually have anything to do with that?

**Comment by oojacoboo** [comment]
Obviously tree-shaking with webpack 2 will help here, but that will only take us so far.

**Comment by qimingweng** [comment]
I'm not sure that this package affects bundle.js in any way. If you create an index.js that is just

``` js
module.exports = (callback) => { callback('<html></html>'); }
```

Is it still 1mb?

**Comment by qimingweng** [comment]
This project is meant for universal js websites

**Comment by oojacoboo** [comment]
@qimingweng it's gong to include all required dependencies and all those deps, deps, etc.  If there aren't any, it shouldn't include anything else.  Obv tree-shaking would kick out some of that.

Thanks for clarifying the intent of the project being isomorphic.  It seems like, for my case, I'm better off just rolling my own custom js if needed, since I'm only aiming for a static site here.  Thanks.
